[package]
name = "vcam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
simple_logger = "4.1.0"
sdl2 = { version = "0.35.2", features = ["gfx"] }
cgmath = "0.18.0"
rand = "0.8.5"
